// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using expenses_analysis;

#nullable disable

namespace expenses_analysis.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240518170805_changeTable")]
    partial class changeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("expenses_analysis.Models.Analytics", b =>
                {
                    b.Property<int>("id_Analytics")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Analytics"));

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<int>("id_Expenses")
                        .HasColumnType("int");

                    b.Property<int>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_Analytics");

                    b.HasIndex("id_Expenses");

                    b.HasIndex("id_User");

                    b.ToTable("Analytics");
                });

            modelBuilder.Entity("expenses_analysis.Models.Budget", b =>
                {
                    b.Property<int>("id_Budget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Budget"));

                    b.Property<int>("id_User")
                        .HasColumnType("int");

                    b.Property<int>("user_Budget")
                        .HasColumnType("int");

                    b.HasKey("id_Budget");

                    b.HasIndex("id_User");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("expenses_analysis.Models.Category", b =>
                {
                    b.Property<int>("id_Category")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Category"));

                    b.Property<string>("category_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_Category");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("expenses_analysis.Models.Expenses", b =>
                {
                    b.Property<int>("id_Expenses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_Expenses"));

                    b.Property<int>("amout_money")
                        .HasColumnType("int");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_User")
                        .HasColumnType("int");

                    b.HasKey("id_Expenses");

                    b.HasIndex("id_User");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("expenses_analysis.Models.Users", b =>
                {
                    b.Property<int>("id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_User"));

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_User");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("expenses_analysis.Models.Analytics", b =>
                {
                    b.HasOne("expenses_analysis.Models.Expenses", "cost")
                        .WithMany()
                        .HasForeignKey("id_Expenses")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("expenses_analysis.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("cost");
                });

            modelBuilder.Entity("expenses_analysis.Models.Budget", b =>
                {
                    b.HasOne("expenses_analysis.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("expenses_analysis.Models.Expenses", b =>
                {
                    b.HasOne("expenses_analysis.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
